### PR TITLE
resolved updated swift code, and fixed internet connectivity issues

### PR DESCRIPTION
**Pull request by ZJaffee**

### CODE REVIEW

**Comment by nickkjordan** [comment]
LGTM.  

What was breaking down in terms of connectivity?

**Comment by ZJaffee** [comment]
When running the app within the newest versions of xcode and ios the runtime error 
```
Transport security has blocked a cleartext HTTP (http://) resource load since it is insecure. 
Temporary exceptions can be configured via your app's Info.plist file.
```
was passed. Basically when the app started up, it would say you weren't connected to the internet.

**Comment by nickkjordan** [comment]
Yep.  Probably need to figure out a way to make secure connections

**Comment by nickkjordan** [comment]
Feel free to merge

**Comment by ZJaffee** [comment]
I don't have write access.

**Pull request merged**
